language: rust
sudo: required
rust:
  - nightly
os:
  - linux
dist: xenial

matrix:
  include:
    - name: "Desktop build"
      addons:
        apt:
          packages:
            - libasound2-plugins
            - libfaad2
            - libfftw3-single3
            - libjack-jackd2-0
            - libmms0
            - libmpg123-0
            - libopus0
            - liborc-0.4-0
            - libpulsedsp
            - libsamplerate0
            - libspeexdsp1
            - libtdb1
            - libtheora0
            - libtwolame0
            - libwayland-egl1-mesa
            - libwebp5
            - libwebrtc-audio-processing-0
            - liborc-0.4-dev
            - pulseaudio
            - pulseaudio-utils

      before_install:
        - curl -L https://servo-deps.s3.amazonaws.com/gstreamer/gstreamer-1.14-x86_64-linux-gnu.20190213.tar.gz | tar xz
        - sed -i "s;prefix=/opt/gst;prefix=$PWD/gst;g" $PWD/gst/lib/pkgconfig/*.pc
        - export PKG_CONFIG_PATH=$PWD/gst/lib/pkgconfig
        - export GST_PLUGIN_SYSTEM_PATH=$PWD/gst/lib/gstreamer-1.0
        - export GST_PLUGIN_SCANNER=$PWD/gst/libexec/gstreamer-1.0/gst-plugin-scanner
        - export PATH=$PATH:$PWD/gst/bin
        - export LD_LIBRARY_PATH=$PWD/gst/lib:$LD_LIBRARY_PATH

      before_script:
        - pulseaudio --start
        - gst-inspect-1.0 | grep Total

      script:
        - cargo build
        - ls examples/*.rs | xargs -I{} basename  {} .rs  | grep -v params_connect | RUST_BACKTRACE=1 GST_DEBUG=3 xargs -I{} cargo ex {} --all-features

    - name: "Android build"
      before_install:
        - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=nightly -y
        - source $HOME/.cargo/env
        - rustup target add arm-linux-androideabi
        - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O ndk.zip
        - unzip ndk.zip > /dev/null
        - export NDK_HOME=`pwd`/android-ndk-r16b
        - ${NDK_HOME}/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir android-21-armv7-toolchain
        - echo "[target.arm-linux-androideabi]" >> examples/android/lib/.cargo/config
        - echo "linker = \"`pwd`/android-21-armv7-toolchain/bin/arm-linux-androideabi-gcc\"" >> examples/android/lib/.cargo/config
        - echo "ar = \"`pwd`/android-21-armv7-toolchain/bin/arm-linux-androideabi-ar\"" >> examples/android/lib/.cargo/config
        - cat examples/android/lib/.cargo/config

      script:
          - cd examples/android
          - source build.sh
