[package]
name = "servo_media_derive"
version = "0.1.0"
authors = ["Fernando Jim√©nez Moreno <ferjmoreno@gmail.com>"]

[lib]
name = "servo_media_derive"
proc-macro = true
path = "lib.rs"

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
