[package]
name = "servo-media-webrtc"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]
license = "MPL-2.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
log = "0.4"
uuid = { version = "1.4", features = ["v4"] }

[dependencies.servo-media-streams]
path = "../streams"
