[package]
name = "servo-media-streams"
version = "0.1.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2018"

[lib]
name = "servo_media_streams"
path = "lib.rs"

[dependencies]
lazy_static = "1.0"
uuid = { version = "1.4", features = ["v4"] }
