[package]
name = "servo-media-streams"
version = "0.1.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2021"
license = "MPL-2.0"

[lib]
name = "servo_media_streams"
path = "lib.rs"

[dependencies]
parking_lot = { workspace = true }
uuid = { version = "1.4", features = ["v4"] }
